### ISSUE TITLE
Implement nginx rate limit to certain routes

### ISSUE THREAD

**Issue by catouberos** [tanamoe/violet#1]
Currently there was no rate limiting method implemented, and since Pocketbase (not yet) supported captcha (https://github.com/pocketbase/pocketbase/issues/731), we should consider rate limiting certain routes?

**Comment by momo-p** [comment]
might not needed rn since most of the record queries are cache friendly

**Comment by catouberos** [comment]
> might not needed rn since most of the record queries are cache friendly

most of them, yes, but some - e.g. create new user query, aren’t protected yet

**Comment by momo-p** [comment]
looking into this
